
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 809)
        MainWindow.setMinimumSize(QtCore.QSize(555, 690))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.full = QtWidgets.QWidget(self.centralwidget)
        self.full.setObjectName("full")
        self.giua = QtWidgets.QWidget(self.full)
        self.giua.setGeometry(QtCore.QRect(10, 10, 951, 131))
        self.giua.setStyleSheet("background-color: rgb(255, 255, 255);\n"
" border-radius: 15px;")
        self.giua.setObjectName("giua")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.giua)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.haui = QtWidgets.QLabel(self.giua)
        self.haui.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.haui.setFont(font)
        self.haui.setFocusPolicy(QtCore.Qt.NoFocus)
        self.haui.setAcceptDrops(False)
        self.haui.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.haui.setStyleSheet("\n"
"image: url(:/newPrefix/HAUI_Logo.png);")
        self.haui.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.haui.setFrameShadow(QtWidgets.QFrame.Plain)
        self.haui.setLineWidth(1)
        self.haui.setText("")
        self.haui.setPixmap(QtGui.QPixmap("../../../HK6-2023/Object_tracking/eaut.jpg"))
        self.haui.setScaledContents(True)
        self.haui.setAlignment(QtCore.Qt.AlignCenter)
        self.haui.setOpenExternalLinks(False)
        self.haui.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.haui.setObjectName("haui")
        self.horizontalLayout_2.addWidget(self.haui)
        self.tenapp = QtWidgets.QLabel(self.giua)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tenapp.setFont(font)
        self.tenapp.setStyleSheet("color: rgb(255, 0, 0);\n"
"")
        self.tenapp.setAlignment(QtCore.Qt.AlignCenter)
        self.tenapp.setObjectName("tenapp")
        self.horizontalLayout_2.addWidget(self.tenapp)
        self.haui_fee = QtWidgets.QLabel(self.giua)
        self.haui_fee.setMaximumSize(QtCore.QSize(110, 16777215))
        self.haui_fee.setMouseTracking(False)
        self.haui_fee.setAutoFillBackground(False)
        self.haui_fee.setStyleSheet("image: url(:/newPrefix/FEE_Logo.png);")
        self.haui_fee.setText("")
        self.haui_fee.setPixmap(QtGui.QPixmap("../../../HK6-2023/Object_tracking/k10.png"))
        self.haui_fee.setScaledContents(True)
        self.haui_fee.setObjectName("haui_fee")
        self.horizontalLayout_2.addWidget(self.haui_fee)
        self.label_4 = QtWidgets.QLabel(self.full)
        self.label_4.setGeometry(QtCore.QRect(10, 700, 201, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.nhandien = QtWidgets.QPushButton(self.full)
        self.nhandien.setEnabled(True)
        self.nhandien.setGeometry(QtCore.QRect(30, 320, 171, 51))
        self.nhandien.setMinimumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setFamily("UTM Avo")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.nhandien.setFont(font)
        self.nhandien.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nhandien.setMouseTracking(True)
        self.nhandien.setTabletTracking(False)
        self.nhandien.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../ĐACN/Biển số xe/Plate_Project/feather/arrow-down-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nhandien.setIcon(icon)
        self.nhandien.setIconSize(QtCore.QSize(30, 30))
        self.nhandien.setCheckable(False)
        self.nhandien.setObjectName("nhandien")
        self.chonanh = QtWidgets.QPushButton(self.full)
        self.chonanh.setGeometry(QtCore.QRect(30, 210, 170, 51))
        self.chonanh.setMinimumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setFamily("UTM Avo")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.chonanh.setFont(font)
        self.chonanh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chonanh.setMouseTracking(True)
        self.chonanh.setStyleSheet("#Inputpicture\n"
"{\n"
"backgroud-color: #fe9f4f;\n"
"}")
        icon1 = QtGui.QIcon()
        self.chonanh.setIcon(icon1)
        self.chonanh.setIconSize(QtCore.QSize(30, 30))
        self.chonanh.setObjectName("chonanh")
        self.xuatfile = QtWidgets.QPushButton(self.full)
        self.xuatfile.setGeometry(QtCore.QRect(30, 430, 170, 51))
        self.xuatfile.setMinimumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xuatfile.setFont(font)
        self.xuatfile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.xuatfile.setMouseTracking(True)
        self.xuatfile.setStyleSheet("#Inputpicture\n"
"{\n"
"backgroud-color: #fe9f4f;\n"
"}")
        self.xuatfile.setIcon(icon1)
        self.xuatfile.setIconSize(QtCore.QSize(30, 30))
        self.xuatfile.setObjectName("xuatfile")
        self.thread2 = QtWidgets.QLabel(self.full)
        self.thread2.setGeometry(QtCore.QRect(300, 160, 561, 471))
        self.thread2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border-radius: 25px;")
        self.thread2.setScaledContents(True)
        self.thread2.setObjectName("thread2")
        self.kq2 = QtWidgets.QLabel(self.full)
        self.kq2.setGeometry(QtCore.QRect(300, 650, 551, 121))
        self.kq2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"border-radius: 25px;")
        self.kq2.setScaledContents(True)
        self.kq2.setObjectName("kq2")
        self.previous = QtWidgets.QPushButton(self.full)
        self.previous.setEnabled(True)
        self.previous.setGeometry(QtCore.QRect(30, 540, 171, 51))
        self.previous.setMinimumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setFamily("UTM Avo")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.previous.setFont(font)
        self.previous.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previous.setMouseTracking(True)
        self.previous.setTabletTracking(False)
        self.previous.setAutoFillBackground(False)
        self.previous.setIcon(icon)
        self.previous.setIconSize(QtCore.QSize(30, 30))
        self.previous.setCheckable(False)
        self.previous.setObjectName("previous")
        self.horizontalLayout.addWidget(self.full)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tenapp.setText(_translate("MainWindow", "ỨNG DỤNG NHẬN DIỆN LINH KIỆN ĐIỆN TỬ"))
        self.label_4.setText(_translate("MainWindow", "KẾT QUẢ"))
        self.nhandien.setText(_translate("MainWindow", "Nhận diện"))
        self.chonanh.setText(_translate("MainWindow", "Chọn ảnh  "))
        self.xuatfile.setText(_translate("MainWindow", "Xuất File"))
        self.thread2.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\"> </span></p></body></html>"))
        self.kq2.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\"> </span></p></body></html>"))
        self.previous.setText(_translate("MainWindow", "PREVIOUS"))
